### ISSUE TITLE
Seattle Neighborhood Greenways rep needs to contact owners of existing GitHub organization

### ISSUE THREAD

**Issue by bry3mason** [StreetsAlliance/DIY_Infrared_Bike-Ped_Counter#1]
Hi,

I am the co-chair of Ballard-Fremont Greenways and our group is currently managing software development projects for Seattle Neighborhood Greenway. I am trying to contact the owners of the existing, but long dormant, "Seattle Neighborhood Greenways" organization on GitHub to discuss a transfer of ownership. The only member of this org appears to be @domoritz .

If you need to confirm my bona fides, please contact the Executive Director of SNG, Gordon Padelford <gordon@seattlegreenways.org>.

Thanks,

Bryant Mason

**Comment by seamaker** [comment]
It's likely me.
Bob Edmiston

**Comment by domoritz** [comment]
Do you still need anything from me? I haven't done anything on this in a decade.

**Comment by bry3mason** [comment]
Addressed by @seamaker. Thanks, Bob!
